In [1]:
import pandas as pd
import numpy as np


In [2]:
###data loading
df1 = pd.read_csv('titanic_dataset.csv')
df2 = pd.read_csv('gender_submission.csv')

In [3]:
df1.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [4]:
df2.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [5]:
df1

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [6]:
###data preprocessing
df2 = df2.drop("PassengerId",axis=1)

In [7]:
df2.head()

Survived
0         0
1         1
2         0
3         0
4         1

In [8]:
###data Preprocessing
df1 = df1.drop(['Pclass','Name','SibSp','Parch','Embarked','Cabin','Ticket','Fare'],axis = 1)

In [9]:
df1.head()

PassengerId     Sex   Age
0          892    male  34.5
1          893  female  47.0
2          894    male  62.0
3          895    male  27.0
4          896  female  22.0

In [10]:
###formation of dataframe
df = pd.concat([df1,df2],axis = 1)

In [11]:
df.head()

PassengerId     Sex   Age  Survived
0          892    male  34.5         0
1          893  female  47.0         1
2          894    male  62.0         0
3          895    male  27.0         0
4          896  female  22.0         1

In [16]:
df.describe()

PassengerId         Age    Survived
count   418.000000  332.000000  418.000000
mean   1100.500000   30.272590    0.363636
std     120.810458   14.181209    0.481622
min     892.000000    0.170000    0.000000
25%     996.250000   21.000000    0.000000
50%    1100.500000   27.000000    0.000000
75%    1204.750000   39.000000    1.000000
max    1309.000000   76.000000    1.000000

In [64]:
### Null and NaN value replacement using pandas
df['PassengerId'] = np.where(df['PassengerId']==0,df['PassengerId'].median(),df['PassengerId'])

df['Age'] = df['Age'].fillna(0)
df['Age'] = np.where(df['Age']==0,df['Age'].median(),df['Age'])

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
### dataframe splitting into feature and labels using numpy
feature = df.iloc[:,:-1]

In [67]:
label = df.iloc[:,-1]

In [68]:
feature.head()

PassengerId     Sex   Age
0        892.0    male  34.5
1        893.0  female  47.0
2        894.0    male  62.0
3        895.0    male  27.0
4        896.0  female  22.0

In [69]:
label.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [70]:
###dropping of column
feature = feature.drop('Sex',axis=1)

In [71]:
feature.head()

PassengerId   Age
0        892.0  34.5
1        893.0  47.0
2        894.0  62.0
3        895.0  27.0
4        896.0  22.0

In [72]:
###splitting into training and testing dataset
x_train,x_test,y_train,y_test = train_test_split(feature,label,test_size = 0.3,random_state = 42)

In [73]:
x_train.head()

PassengerId   Age
118       1010.0  36.0
271       1163.0  24.0
114       1006.0  63.0
311       1203.0  22.0
131       1023.0  53.0

In [74]:
x_train.shape,x_test.shape

((292, 2), (126, 2))

In [75]:
df.shape

(418, 4)

In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
###model loading
model = RandomForestClassifier()

In [78]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [81]:
predicted = model.predict(x_test)

In [82]:
print(predicted)

[0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0]


In [114]:
from sklearn.metrics import accuracy_score, classification_report

In [83]:
score = accuracy_score(predicted,y_test)

In [84]:
print(score)

0.5396825396825397


In [127]:
model.predict([[5005,24]])

array([0], dtype=int64)

In [85]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()

In [86]:
model1.fit(x_train,y_train)

GaussianNB()

In [87]:
predicted1 = model1.predict(x_test)

In [88]:
print(predicted1)

[0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [89]:
score1 = accuracy_score(predicted1,y_test)

In [90]:
print(score1)

0.6507936507936508


In [124]:
model1.predict([[1000,24]])

array([0], dtype=int64)

In [92]:
from sklearn import svm

In [94]:
model2 = svm.SVR()

In [95]:
model2.fit(x_train,y_train)

SVR()

In [96]:
predicted2 = model2.predict(x_test)

In [97]:
print(predicted2)

[0.09975814 0.09995419 0.10000242 0.10025704 0.09990193 0.10031918
 0.10020505 0.10014053 0.0996297  0.1002511  0.10056046 0.10056088
 0.10009457 0.10051403 0.10022734 0.10038524 0.10029014 0.1005397
 0.10038734 0.10015701 0.10065176 0.09981552 0.09986935 0.099811
 0.09969378 0.10004486 0.09992745 0.09989542 0.10000836 0.10017547
 0.0997623  0.09989893 0.09993078 0.10012372 0.09968739 0.09973571
 0.10018898 0.099701   0.09970911 0.10018226 0.10023203 0.10041554
 0.10004308 0.09968442 0.10020208 0.0996434  0.09991785 0.10050718
 0.10016074 0.09980596 0.10051035 0.10037635 0.09966785 0.10049694
 0.10001499 0.099636   0.10020324 0.09993721 0.0995764  0.10010262
 0.10033746 0.09993756 0.09982728 0.09983843 0.09978949 0.09986587
 0.10029725 0.09987051 0.09998229 0.10050767 0.10020155 0.09973078
 0.09992194 0.10047143 0.100271   0.09994692 0.09986939 0.10014339
 0.09984094 0.10029084 0.09998192 0.10034685 0.10051828 0.10027924
 0.0999012  0.10042567 0.10016542 0.09968087 0.09967899 0.0997171

In [100]:
rounded = np.round(predicted2)

In [101]:
print(rounded)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [102]:
score2 = accuracy_score(rounded,y_test
                       )

In [103]:
print(score2)

0.6746031746031746


In [126]:
np.round(model2.predict([[1000,24]]))

array([0.])

In [111]:
from sklearn.metrics import confusion_matrix

In [113]:
confusion_matrix(predicted,y_test)

array([[59, 32],
       [26,  9]], dtype=int64)

In [116]:
target_names = ['0', '1']
print(classification_report(y_test,predicted, target_names=target_names))

              precision    recall  f1-score   support

           0       0.65      0.69      0.67        85
           1       0.26      0.22      0.24        41

    accuracy                           0.54       126
   macro avg       0.45      0.46      0.45       126
weighted avg       0.52      0.54      0.53       126



In [118]:
confusion_matrix(predicted1,y_test)


array([[79, 38],
       [ 6,  3]], dtype=int64)

In [119]:
target_names = ['0', '1']
print(classification_report(y_test,predicted1, target_names=target_names))


              precision    recall  f1-score   support

           0       0.68      0.93      0.78        85
           1       0.33      0.07      0.12        41

    accuracy                           0.65       126
   macro avg       0.50      0.50      0.45       126
weighted avg       0.56      0.65      0.57       126



In [120]:
confusion_matrix(rounded,y_test)


array([[85, 41],
       [ 0,  0]], dtype=int64)

In [121]:
target_names = ['0', '1']
print(classification_report(y_test,rounded, target_names=target_names))

              precision    recall  f1-score   support

           0       0.67      1.00      0.81        85
           1       0.00      0.00      0.00        41

    accuracy                           0.67       126
   macro avg       0.34      0.50      0.40       126
weighted avg       0.46      0.67      0.54       126



C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
